definitions:
  controllers.EmailResponse:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
  controllers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controllers.LoginResponse:
    properties:
      message:
        type: string
      token:
        type: string
    type: object
  controllers.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  controllers.RegisterResponse:
    properties:
      message:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/GetCurrentUser:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.EmailResponse'
      security:
      - BearerAuth: []
      tags:
      - GetCurrentUser
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: LoginRequest
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginResponse'
      tags:
      - Login
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: RegisterRequest
        in: body
        name: request
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RegisterResponse'
      tags:
      - Register
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
